### ISSUE TITLE
Database Rework

### ISSUE THREAD

**Issue by JayDwee** [KoalaBotUK/KoalaBot#106]
### What Koala extension does this refer to (if applicable)
Whole of Koala

### Is your feature request related to a problem? Please describe.
Current SQLite solution has security and backup issues. Moving to another database implementation would be ideal.

### Describe the solution you'd like
MySQL seems like the best idea, but it is good to look into other options.
We want to be able to host Koala databases on a separate machine and connect to it remotely.
We want to have a better encryption that doesn't require SQLcipher (which only works on linux). 
We want backups to be stored of the database in case anything wrong happens.
It would be ideal to also have the option of a distributed system so if one database is knocked offline, others can take its place.
It would also be nice if we could host a database easily for each of our developers to help with development.

### Describe alternatives you've considered
MySQL, PostgreSQL or amazons offering. Although Ideally a free solution should be chosen to then be deployed on our own servers.

### Additional context
N/A

### Subtasks
- [x] #179 
- [x] #224 
- [x] #222

**Comment by ChrisF999** [comment]
So some aspects that need to be considered from a frontend perspective is the ORM (Object-relational mapping) library we use to simplify the database management only currently supports SQLite, PostgreSQL and MySQL databases. If we move to another solution a large portion of work would be required for the frontend to keep up and maintain the level of integration needed.

**Comment by JayDwee** [comment]
Deployed on DEV2, needs full testing

**Comment by Gave2Haze** [comment]
See 'koala-dev2' tab in the [test plans](https://drive.google.com/drive/folders/1kj5pqQ95gbiidRh08uLOezL8ATELCOrQ) for pass/fail details. There are also other minor issues and clarifications that aren't worth reporting at this time on there, e.g. inconsistent error messages.

- Verify: IntegrityError bug when using the `k!verifyAdd` command, this blocked testing of all but two verify commands.
- TwitchAlert: All commands returned a CommandNotFound error message
- Vote: `vote setEndTime` failed, the votes did not end at the specified time. Also, `vote cancel` does not cancel the vote from being sent out even if sent immediately after `vote send`.

**Comment by Gave2Haze** [comment]
- RFR: Unexpected error message after inputting RFR message ID on most tests, all of which failed. Inputting `all` during the `rfr edit inline` process did not result in an error message but did not seem to work anyway.
`rfr create` and `rfr addRequiredRole` both gave an IntegrityError message but the former passed while the former did not, resulting in a couple of tests being blocked.

- ColourRole: `addCustomColourAllowedRole` and `addProtectedRoleColour` both gave IntegrityError messages and blocked testing of all but two other commands. `customColour` continues to give a CheckFailure error despite being blocked.
- TextFilter:  Given that I haven't tested this before, I'm not confident that I did so correctly or thoroughly. 
Having said that, `modChannelAdd` failed due to no reports being sent to the channel. `ignoreChannel` failed only when inputting 'koala-dev2', and gave a DataError.

**Comment by Gave2Haze** [comment]
- Announce: All commands passed, however `announce send` gave an IntegrityError after entering the command.

**Comment by JayDwee** [comment]
Remaining: Bug fixing & Backing up / error handling

**Comment by Gave2Haze** [comment]
See 'koala-alpha' tab in the [test plans](https://drive.google.com/drive/folders/1kj5pqQ95gbiidRh08uLOezL8ATELCOrQ) for pass/fail details. There are also other minor issues and clarifications that aren't worth reporting at this time on there, e.g. inconsistent error messages.

- Verify: After using `k!reVerify` to remove roles, I was unable to verify again to get the same roles using `k!confirm` until I removed and readded the role/domain pair.
- ReactForRole: Possible unintended behaviour with `rfr addRequiredRole` and `rfr removeRequiredRole`; I was able to react to rfr messages whether I had the required role or not, however I was given and not given the role I reacted to (respectively) as intended. Other questionable behaviour included: using an image format not previewed by discord (.avif) resulted in the rfr message having no thumbnail, and one occurence of having a react emoji (by the bot) under an rfr message that wasn't in a role/domain pair in the message itself. However it went away when I reacted with the same emoji with an account with a required role.
Here are the definite fails for the RFR module: mentioning a role with the `rfr edit removeRoles` command returned the message "No emoji found" and a "TypeError - cannot unpack non-iterable coroutine object" error message. Inputting an emoji with the same command returned just the same "TypeError" error message.
Editing inline properties with the `rfr edit inline` command only worked when typing `y` (yes) during the process to choose inline fields on a default message; after changing a default message therefore I was unable to revert it by typing `n` (no) during the process.
The `rfr edit fixEmbed` command continues to give the "Forbidden - 403 Forbidden (error code: 50013): Missing Permissions" error message after inputting the rfr message id.

**Comment by Gave2Haze** [comment]
- Announce: No fails

**Comment by Gave2Haze** [comment]
- Colour Role: No fails, however got a `CheckFailure` error message after attempting to use the `customColour` command without the correct role.

**Comment by Gave2Haze** [comment]
- Vote: No fails yet. Some commands give a checkfailure if the string is not inputted after the command (should give a MissingRequiredArgument instead). Also `k!vote close` gives a `KeyError` message if the wrong title string is given.
- Text Filter: both the `modChannelAdd` and `modChannelRemove` commands fail; the former as only banned words were reported in the selected channel, not risky ones, and the latter because it does not work using the mention of a channel (e.g. #alpha) but does using the channel ID.

**Comment by Gave2Haze** [comment]
- TwitchAlert: `editMsg` fails when used with `#koala-alpha` channel (gives an AttributeError) but works fine with `#koala-dev2`
-

**Comment by JayDwee** [comment]
> Some commands give a checkfailure if the string is not inputted after the command (should give a MissingRequiredArgument instead).

This is unfortunately a limitation of our library, not the easiest thing to overcome (slash commands should fix this issue)

**Comment by JayDwee** [comment]
> Vote: k!vote setEndTime fails, the vote just doesn't end on time. 

Assuming timezone related issue as discussed

**Comment by JayDwee** [comment]
> the former as only banned words were reported in the selected channel

Expected behaviour. Could be useful to add, however with AutoMod from Discord I don't believe we will do much further work on TextFilter

**Comment by Gave2Haze** [comment]
> mentioning a role with the rfr edit removeRoles command returned the message "No emoji found"
still gives this message but then works straight after and gives the second successful message

> The `rfr edit fixEmbed` command
not yet tested on another server

everything else has passed now

**Comment by JayDwee** [comment]
>> mentioning a role with the rfr edit removeRoles command returned the message "No emoji found"

>still gives this message but then works straight after and gives the second successful message

Fixed
