### ISSUE TITLE
Add new developers to README or equivalent

### ISSUE THREAD

**Issue by JayDwee** [KoalaBotUK/KoalaBot#123]
### What Koala extension does this refer to (if applicable)
N/A

### Is your feature request related to a problem? Please describe.
New developers aren't shown on the Readme currently.

### Describe the solution you'd like
Ideally all developers will be removed from the list and instead devs should be shown elsewhere within the repo, or directed to the website
Alternatively all new devs can be added to the authors section (decision on what to do about frontend/backend teams will need to be made)

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by ChrisF999** [comment]
All new devs are present on the wip homepage we could look into a partial deployment for just that page.

**Comment by JayDwee** [comment]
Completed in 6b41433d5ec364dc1044e1776fc755d40551dbb6
