### ISSUE TITLE
Vote doesn't handle DMs being blocked

### ISSUE THREAD

**Issue by largereptile** [KoalaBotUK/KoalaBot#160]
### Describe the bug
Vote loop to send polls stops upon attempting to send it to a user who doesn't accept dms.

### To Reproduce
Numbered steps to reproduce the behavior:
1. Create a vote that would target yourself
2. Disable DMs from non-friends etc.
3. Send vote

### Expected behaviour
Vote sends to every user with the role/voice channel specified.

### Screenshots
![image](https://user-images.githubusercontent.com/22501149/116790007-029df280-aaaa-11eb-93e4-e84e2d945291.png)

**Comment by JayDwee** [comment]
If the chair has DMs disabled, another error occurs and doesn't show the vote results. Then essentially loses the result. Either a check for this before setting the chair, or a fall back to channel message is needed.

![image](https://user-images.githubusercontent.com/30408869/116791121-1ba9a200-aab0-11eb-9e71-8e79703ad813.png)
