### ISSUE TITLE
Making data type for channel_id the same in all database models

### ISSUE THREAD

**Issue by JCoder00** [KoalaBotUK/KoalaBot#179]
### Describe the bug
Currently, the data type for 'channel_id' differs across the different models within the database. It should preferably have the same data type across all models.
The only model that is different from the rest is textFilterModeration, which is currently set as a `String`

### To Reproduce
Numbered steps to reproduce the behavior:
1. Run `npx prisma studio`
2. Open up models 'TwitchAlerts' and 'TextFilterModeration'
3. See data type for 'channel_id'

### Expected behaviour
'channel_id' should have data type set as `int` for all models

### Screenshots
![image](https://user-images.githubusercontent.com/72449232/118638843-29a93380-b7cf-11eb-93b0-a7ed8671b7df.png)
![image](https://user-images.githubusercontent.com/72449232/118638891-37f74f80-b7cf-11eb-90d3-a2ebae451766.png)

### Additional context
N/A

**Comment by JayDwee** [comment]
completed as part of #106
