### ISSUE TITLE
Error on Koalabot's main READ.md

### ISSUE THREAD

**Issue by SnowyJaguar1034** [KoalaBotUK/KoalaBot#209]
### Describe the bug
The `See also the list of current developers who are actively participating in this project` in the main READ.md returns a 404 error error when clicked

### To Reproduce
Numbered steps to reproduce the behavior:
1. Go to '[Koala Bot On GitHub](https://github.com/KoalaBotUK/KoalaBot).'
2. Click on See also the list of [current developers](https://github.com/orgs/KoalaBotUK/teams/developers] who are actively participating in this project.'
3. See error

### Expected behaviour
A page showing KoalaBot's developers, I've never seen the page before so I can't describe what it looks like.

### Screenshots
![image](https://user-images.githubusercontent.com/51423344/122418844-6a3cce00-cf82-11eb-9d09-be6b11ff5de7.png)
### Contact Information (optional):
 - Discord: SnowyJaguar#1034

**Comment by JayDwee** [comment]
Thanks, looks like the team link requires someone to be in the organisation to view. 
Best fix is to probs use the contributors link for backend. I'll get on this soon
