### ISSUE TITLE
Guilds Database Invalid Foreign Keys

### ISSUE THREAD

**Issue by JayDwee** [KoalaBotUK/KoalaBot#222]
### Describe the bug
Currently, as can be seen in the ER diagram, each koala extension uses the GuildExtensions table for their foreign key (Fig 1). However, guild_id in GuildExtensions cannot be used as it is within a composite key.

### To Reproduce & Expected behaviour
see https://github.com/KoalaBotUK/KoalaBotFrontend/issues/137

### Recommended Fix
Create a `Guilds` table with the fields:
- `guild_id` 
- `subscription` (indication of if the discord guild has Koala Pro or similar), format should be same as `subscription_required` in KoalaExtensions (indicator of which extensions can be used)

As subscriptions have not been added yet, functionality of this aspect is not required.

All current tables using GuildExtensions.guild_id as a foreign key should be altered to use the new Guild.guild_id. Including `GuildExtensions` and any tables that were not correctly added as foreign keys before (see Fig 2).

Update the ER diagram with the new approach before development, sending to the other senior devs for approval of the new approach.

This fix will need to work with all previous Koala database versions. To do this you will likely need to check if the new table exists and which tables connect to it and overwrite if in the old form, leaving if in the new form. This should allow anyone to deploy the new version without wiping their database.

### Screenshots
![image](https://user-images.githubusercontent.com/30408869/125809760-0afd5d78-813d-4f9d-b5df-4a7ef748bc7c.png)
Fig 1

![image](https://user-images.githubusercontent.com/30408869/125811299-4c648142-f8ad-4446-b610-4ae49ca41e62.png)
Fig 2

### Additional context
Believe this issue can fix https://github.com/KoalaBotUK/KoalaBotFrontend/issues/137 from the frontend

**Comment by Kaspiaan** [comment]
- Alter tables where no fk costraint exists to add the Guilds/guild_id fk
 - Alter ER diagram to include fk constraints where diagram is incorrect (i.e. ![text filter](https://user-images.githubusercontent.com/57161931/126978055-d158ba4c-fe44-4a4f-9755-2d02af26ab4d.png) )

**Comment by JayDwee** [comment]
completed as part of #106
