### ISSUE TITLE
Store guild_id / channel_id as Strings, not Integers

### ISSUE THREAD

**Issue by stefan-cooper** [KoalaBotUK/KoalaBot#224]
### Describe the bug
`guild_id` and `channel_id` are returned as a String by the Discord API (see https://discord.com/developers/docs/resources/guild#get-guild)

Currently, we convert these to Integers. While this seems to be okay in Python and SQLite is happy to store them like that, JS is not. JS has a [max safe integer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER) of 9007199254740991. JS will handle converting the returned String to an Integer but will round the end of the number to make it safe to use. When we then try to use this rounded number later on (as it will have been stored in our database like this), it causes problems because it doesn't exist.

### Expected behaviour
We should just store these as the Strings that the Discord API returns. 

### Additional context
This is a **blocker** going forward for the Frontend team, as we cannot properly handle actual Discord data without the IDs being rounded incorrectly.

**Comment by JayDwee** [comment]
completed as part of #106
