### ISSUE TITLE
Frontend documentation.json changes

### ISSUE THREAD

**Issue by Jamesflynn1** [KoalaBotUK/KoalaBot#237]
### What Koala extension does this refer to (if applicable)
N/A (automatic documentation generation)

### Is your feature request related to a problem? Please describe.
From an inexperienced users' perspective finding information about cogs/commands is a challenge.
Changes have been made to the frontend website to accommodate new fields to help users better understand cogs and commands.

### Describe the solution you'd like
The following fields added to the documentation.json file:
A filename (to provide a link to the docs) for each cog
A description for each cog
An example for each command
A parameter consisting of a name and whether or not it's required and a description

### Describe alternatives you've considered
N/A

### Additional context
An example of a Json file in the desired format.
[documentation.json](https://github.com/KoalaBotUK/KoalaBot/files/6924019/documentation.txt)

Linked with #203

**Comment by stefan-cooper** [comment]
Can this be closed? I see that the [documentation.json](https://github.com/KoalaBotUK/KoalaBot/blob/master/documentation.json) has been merged, is it fully up to date?
