### ISSUE TITLE
[RFR] RFR Message breaks when reacting with a Unicode emoji after setup

### ISSUE THREAD

**Issue by Unknownlocal** [KoalaBotUK/KoalaBot#245]
### Describe the bug
After adding a Unicode emoji, RFR message will not add/remove roles correctly once someone reacts with a Unicode emoji, then removes all emoji options one by one. Does not get fixed by `fixEmbed`

### To Reproduce
Numbered steps to reproduce the behaviour:
1. `k!rfr create` - Create an RFR Message
2. `k!rfr edit addRoles`, then add an `<emoji>,<role>` combination with at least one Unicode emoji, e.g. 3️⃣
3. React to message after setup with a Unicode Emoji

### Expected behaviour
Add correct role associated with emoji to person who reacted, don't remove emoji, role and reaction from RFR message after react.

### Screenshots
![image](https://user-images.githubusercontent.com/16153800/129075849-a98f0a32-0419-49da-b2c8-056c35403a1b.png)

### Additional context
Add any other context about the problem here, as well as the version of KoalaBot this affects.
Seen on v0.4.3

**Comment by JayDwee** [comment]
Closed because it was solved previously
