### ISSUE TITLE
Removing animated emoji reaction from RFR message doesn't remove role

### ISSUE THREAD

**Issue by Unknownlocal** [KoalaBotUK/KoalaBot#246]
### Describe the bug
After reacting to an RFR message with an animated emoji, the role is added correctly. However, after removing this reaction, the role is not removed correctly.

### To Reproduce
Numbered steps to reproduce the behaviour:
1. Setup an RFR message with `k!rfr create` and `k!rfr edit addRoles`, and add at least one animated emoji to the options
2. React with animated emoji - role is added correctly
3. Remove the reaction from step 2
4. Role gained is not removed

### Expected behaviour
Role gained from reaction to RFR message should be removed after removing reaction.

### Screenshots
![image](https://user-images.githubusercontent.com/16153800/129077035-9fc3ce7b-2fa1-47d8-a235-a39573f2bb62.png)
![image](https://user-images.githubusercontent.com/16153800/129077099-b6d64642-9ffa-4770-b1ed-0cb591468436.png)
![image](https://user-images.githubusercontent.com/16153800/129077117-088a2435-8620-442c-953f-6af6e826963a.png)

### Additional context
Add any other context about the problem here, as well as the version of KoalaBot this affects.
Seen in 0.4.3

**Comment by JayDwee** [comment]
Need to test if already completed

**Comment by MikaCrny** [comment]
issue could not be replicated when repeating the steps above on a local clone of the bot, assumed could be completed but can not be certain.

**Comment by Gave2Haze** [comment]
Issue could not be replicated either, however we were unable to use the exact emoji used by Unknownlocal when they reported the bug. As such, I will close the issue as not planned for now as cannot be certain it has been completed.
