### ISSUE TITLE
Base cog API doesn't work on postman

### ISSUE THREAD

**Issue by JayDwee** [KoalaBotUK/KoalaBot#388]
### Describe the bug

tried on postman, doesn't work

### To Reproduce

go postman, try. fail

### Expected behaviour

work

**Comment by abluey** [comment]
To give a slightly more in-depth explanation:

The routes(?) are not accepting JSON content and I do not know why or where to set the headers.

Tests pass because body is being passed with `data=` instead of `json=`; if they are passed with `json=` then it does not pass
