### ISSUE TITLE
Verification Removal & Reassignment

### ISSUE THREAD

**Issue by JayDwee** [KoalaBotUK/KoalaBot#97]
### What Koala extension does this refer to (if applicable)
Verify

### Is your feature request related to a problem? Please describe.
Some people lose their previous discord accounts due to hacking or forgotten details. In this case they will create a new account, and won't be able to verify their email again.

### Describe the solution you'd like
1. **Ensure the user wants to transfer.** Instead of saying `That email is already verified`, the bot should say `That email is currently verified. Would you like to transfer the verification?`.
2. **Verify the new account.** Same approach as usual verification. During this step the old account will continue to be verified until the verify confirmation is given by the new account
3.  **Unverify previous account** Once verified that the user has access to the account, the previous verified user will have that email removed from their verification on our databases, and every discord server that has a verification role given, will be removed. This should also be implemented by `k!unVerify`

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by Gave2Haze** [comment]
Failed during step 2: role is removed from old account before the new account is even verified. To be precise it is removed when the used replies 'y' on the new account when the bot asks 'This email is already assigned to a different account. Would you like to verify anyway? (y/n)'.
